language: java
sudo: false
install: true
addons:
  sonarqube:
    organization:tfg
    token:
      secure:webbxegHt3gILcOtbUymh727He57QolSyj3REFcMh2uXSfF7C74C9n94fnE8DoANnqO0Z6BAdgwT6kgkoZSvrFUVikk7+YBxIohQ9oT8zFOwhMiFkuMtSVPJPuQ6cqxbgweBw10gJMRYrQPAG7Aeyx3FSbntLyW/uBB9dHDIyJ1a93D/iUustX/iHlp1/+8n4ub4FRFUuMDP82MskoY0LaTr5dqErUfP51UgnG3ZIDY3c6IaF156TV0L6x5bTIbuftIz8gBrgxBQ4Pd7TOgNA/Db2kXfcyDJ48pBLKpNsuyhBlAAOIp3x90+kHp/TDXRtOaR1938varzR/thrabCKTm3/sQbKHu70hVwkE5bW3kHpl9cYMGo4UeBGkmv7LWGxV/Fl4GPaR4gworyApOGc6IehY6gSUqh1gA9f3Bh+XQ667sWdCMNx0iwJPA4hSOSfNnONCBSZBEJjjJeHzsUvAIPdaDvvoKFj2/Wr8XskqdcgrOXtw+A1hRZE8uWsHoWGHrlYCKL7dHhrfmQNwNXhB6cM2zH52iMN77v5BfbKTnN75iuHJBwLDd1S8tWqEZhCa6oFOQHVHPSt+TrBK/HBiWXmRANhSrZd+8KgXF3zN0FTgUy4qk0uT04MBiwtqyn8Tw/oB8pI5Njucx1SultE0zDo+FlyR2MDX8sjzX0FC4=
jdk:
  - oraclejdk8
script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'