language: java
sudo: false
install: true
addons:
  sonarqube:
    organization:tfg
    token:
		secure:"V5PoVosaXTiLimemaTMJMETwaOThNz7wg0oNXwiPkBO/k1Af070rLR7uYtDq/XEhjofAMH+xUgaY6qpmu5hL7ExPJQMSlO2WCJ4AyZgmm8T/HizU5aXVfs157MFSta8PZjoc+nSskrOvSThura6D5jQeynd2zPrGc0muDsMb+jYheHNs0QRqm+XLsDu5/S3vPnUHwDVl8BYdb29E95czT2RPiAA1ma05cnb7RdRiQtxhCueNwZbWnAa/hG+T0qIilhskSlz6JoakacKwW3r6STY6PlyZL99Ko/Q1S2hPsuuXYOfsdn1LaY1yECLxUvyKGVv+fvKEcm3IjoxOoIX4+3Kfpbv7wc3Cj79n3mVkJXv6QCQoY7pRkI6CtS3/InRhFFue72LcNoJGEdIv1MVOMIgdkakaVjJuYmc95HtKVz1BQE5j5DTHKBffYvI/EFF439IXFXMrRo99UDmoTuJfHjgZQejh6MQwtbk3rF5IvQUausJ6v/SSVQSWsL7BzfZQD4YFBqnd6WHi1gG56JJVuOCGXRVUbAUDF0RVKVJZYlcUuQfge4ZveZEmOYaNfUuNmp36bNul99CRr0qDkIlC5gono4qjheqj7TmE0IW+z9SzEF+khmaSeO5t008DAYNutMeN3r7+wQuFPD/3PTHbVtFVwu1GmZpYU48/ooe21Rs="
jdk:
  - oraclejdk8
script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'